nameDisplay: Example of excluding players from tournament stages
nameInternal: excludedPlayersTest1

games:
  - name: breakthrough
    url: http://games.ggp.org/base/games/breakthrough/
    numRoles: 2
    fixedSum: true

stages:
  - format: swiss2
    rounds:
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
    playerCutoff: 6
  - format: swiss2
    rounds:
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
    playerCutoff: 4
    excludedPlayers: 
      - 2
  - format: swiss2
    rounds:
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
    playerCutoff: 2
    excludedPlayers: 
      - 4
  - format: swiss2
    excludedPlayers: 
      - 5
      - 6
    rounds:
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
            