games:
  - name: breakthrough
    repository: games.ggp.org/base
    numRoles: 2
    fixedSum: true
  - name: cephalopodMicro
    repository: games.ggp.org/base
    numRoles: 2
    fixedSum: true

nameDisplay: Sample single-elimination tournament
nameInternal: singleElim

stages:
  - format: singleElimination1
    rounds:
      - startTime: Fri, 4 Dec 2015 10:00:00 -0800 PST
        matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
      
    