nameDisplay: Sample Swiss tournament, includes match weights
nameInternal: swiss2Sample6

games:
  - name: game1
    url: http://games.ggp.org/base/games/game1/
    numRoles: 1
    fixedSum: false
  - name: game2
    url: http://games.ggp.org/base/games/game2/
    numRoles: 2
    fixedSum: true
  - name: game3
    url: http://games.ggp.org/base/games/game3/
    numRoles: 2
    fixedSum: false
  - name: game4
    url: http://games.ggp.org/base/games/game4/
    numRoles: 3
    fixedSum: true
  - name: game5
    url: http://games.ggp.org/base/games/game5/
    numRoles: 3
    fixedSum: false

stages:
  - format: swiss2
    rounds:
      - matches:
          - game: game1
            startClock: 60
            playClock: 15
            weight: 0.8
      - matches:
          - game: game2
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game2
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game3
            startClock: 60
            playClock: 15
            weight: 0.75
      - matches:
          - game: game3
            startClock: 60
            playClock: 15
            weight: 0.75
      - matches:
          - game: game4
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game4
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game4
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game4
            startClock: 60
            playClock: 15
            weight: 0.5
      - matches:
          - game: game5
            startClock: 60
            playClock: 15
            weight: 1.0
      - matches:
          - game: game5
            startClock: 60
            playClock: 15
