nameDisplay: Sample Swiss tournament, 2p fixed sum games and 1p games
nameInternal: swiss1Sample2

games:
  - name: breakthrough
    url: http://games.ggp.org/base/games/breakthrough/
    numRoles: 2
    fixedSum: true
  - name: cephalopodMicro
    url: http://games.ggp.org/base/games/cephalopodMicro/
    numRoles: 2
    fixedSum: true
  - name: puzzle1
    url: http://games.ggp.org/base/games/puzzle1/
    numRoles: 1
    fixedSum: false
  - name: puzzle2
    url: http://games.ggp.org/base/games/puzzle2/
    numRoles: 1
    fixedSum: false

stages:
  - format: swiss1
    rounds:
      - matches:
          - game: puzzle1
            startClock: 120
            playClock: 10
            seedRoles: [0]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: breakthrough
            startClock: 60
            playClock: 15
            seedRoles: [0, 1]
      - matches:
          - game: puzzle2
            startClock: 120
            playClock: 10
      - matches:
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
      - matches:
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
      - matches:
          - game: cephalopodMicro
            startClock: 60
            playClock: 15
            seedRoles: [1, 0]
      
    